Fixed the voice call zone
DiscordStyles/Fluent pull request #125
Opened 2024-04-13 23:31 UTC by MidyGamy

so I had a display problem after installing the theme and noticed it was due to the "Show Voice Users" option of discord.
So I made this so the activity panel and actions button adapt to that list.

I also brought back the link to get back the vc channel.

2024-04-13 23:42 UTC, MidyGamy commented
Before (actions buttons don't shows up)
![image](https://github.com/DiscordStyles/Fluent/assets/95078425/18703569-0672-47c2-b043-412c80eb4c10)

After
![image](https://github.com/DiscordStyles/Fluent/assets/95078425/6f62059a-d12b-463a-a4cb-6102bf47aa9a)

2024-04-13 23:43 UTC, MidyGamy commented
btw it also fixes an incomatibility with Vencord "Game Activity Toggle" plugin

2024-04-13 23:58 UTC, Gibbu commented on bd-scss.config.js
This doesn't need to be included in the PR.

2024-04-13 23:59 UTC, Gibbu commented on package-lock.json
This also doesn't need to included in the PR as the repo uses PNPM not npm.

2024-04-14 00:01 UTC, Gibbu commented on src/theme/sidebar/_panels.scss
> +			z-index: 0;
Please move the top level rules before the children rules.
Example:
```scss
&:has(+ .wrapper_e832ee:not(:empty)) {
  z-index: 1;
  .wrapper_e832ee > & {
    margin-bottom: calc(100% - 3px);
  }
}
```

2024-04-14 00:01 UTC, MidyGamy commented
so do I remove it and add it to the .gitignore?

2024-04-14 00:01 UTC, Gibbu requested changes
Please fix the issues and I'll gladly accept.

2024-04-14 00:02 UTC, Gibbu commented
No, just use PNPM. It's much better in every way than npm.

2024-04-14 00:14 UTC, Gibbu requested changes

2024-04-14 00:14 UTC, Gibbu commented on .gitignore
Adding `bd-scss.config.js` to the gitignore file will make it so all future changes to the file will be ignored.

2024-04-14 00:14 UTC, Gibbu commented on bd-scss.config.js
Removing the file from the PR and removing it from the repo are two very different things.
This is telling git to remove it from the repo (which we don't want).

2024-04-14 00:19 UTC, MidyGamy commented
ok so how do I tell the PNPM command to set the output to Vencord?

2024-04-14 00:24 UTC, Gibbu commented
It's not an pnpm command, it's a node command. 
PNPM is the package manager that is used to download the `bd-scss` package and all it's dependencies, which also happenes to run node commands. You can stlll use `npm run dev` and change the bd-scss config file accordingly.

Don't don't add the `bd-scss.config.js` changes to the repo.

2024-04-14 00:25 UTC, MidyGamy commented
ok

2024-04-14 00:26 UTC, MidyGamy commented
should be good now

2024-04-14 00:26 UTC, Gibbu approved these changes

2024-04-14 00:26 UTC, merged